services:
  node:
    image: node:22
    user: node
    working_dir: /home/node/apeframework
    command: tail -f /dev/null
    ports:
      - ${PORT:-3000}:3000
    volumes:
      - .:/home/node/apeframework
